### ISSUE TITLE
Chapter 3  Source Code Issue

### ISSUE THREAD

**Issue by raelpty** [PacktPublishing/Graph-Machine-Learning-#4]
I tried to run the code "01_Shallow_Embeddings.ipynb" unfortunately when I try to run this excerpt :
from gem.embedding.gf import GraphFactorization

G = nx.barbell_graph(m1=10, m2=4)
draw_graph(G)

gf = GraphFactorization(d=2,  data_set=None,max_iter=10000, eta=1*10**-4, regu=1.0)
gf.learn_embedding(G)

I have the following error : 
./gf not found. Reverting to Python implementation. Please compile gf, place node2vec in the path and grant executable permission
		Iter id: 0, Objective: 95.0097, f1: 95.0035, f2: 0.00623775

The error is located specifically with this instruction:  gf.learn_embedding(G)

**Comment by amarzullo24** [comment]
Dear @raelpty,
That is not exactly an error: the GEM library is warning you that it is not able to find the C++ executable. Therefore the Python implementation will be used. This means that you can still compute the embeddings, just slower.

If you want GEM using the C++ implementation you should compile it, as reported on the [original GEM repository](https://github.com/palash1992/GEM/issues/86)

Notice that, once compiled, the executable **gf** needs to be put in the c_exe directory (which is where the `learn_embedding` method will [look for it](https://github.com/palash1992/GEM/blob/5da663255da28c433c42b296c8ceed7163f2d509/gem/embedding/gf.py#L94)). Eventually, be sure to properly configure the system path and give rights to the executable.

**Comment by zf-wei** [comment]
hi emmeduz. I put the complied gf file in the c_exe folder and give it x permission. But it is still not found. What should I do?

**Comment by deeptisingh113** [comment]
I also got the same issue, even after compiling the gf file.
