### ISSUE TITLE
Codes cannot be run in Chap 4?

### ISSUE THREAD

**Issue by icyyyyy730** [PacktPublishing/Graph-Machine-Learning-#5]
Dear authors,

I like your book very much and it helped me get a lot of useful insights, but I have a problem when I do the implementation.

I ran the codes of Graph Classification using GCNs in Chapter04/04_Graph_Neural_Networks.ipynb, but when I try to train the model using the command history = model.fit(
    train_gen, epochs=epochs, verbose=1, validation_data=test_gen, shuffle=True,
)

I got an error:
UnimplementedError:  Cast string to float is not supported
	 [[node binary_crossentropy/Cast (defined at <ipython-input-16-80092151acd1>:2) ]] [Op:__inference_train_function_2594]

Function call stack:
train_function

It seems like the model used a string, but I'm not very good at python and I'm not able to fix the bug, could you please help me with this? Thank you very much!

**Comment by amarzullo24** [comment]
Dear @icyyyyy730,
Thanks for notice this. The last commit should fix it.

If you have further troubles feel free to reopen!
